local colors = require('spacegray.colors')

local M = {}

function M.setup()
  local theme = {}
  local colors = colors.setup()

  theme.base = {
    Bold = { style = 'bold' },
    Boolean = { link = 'Constant' },
    Character = { link = 'Constant' },
    ColorColumn = { bg = colors.gray },
    Comment = { fg = colors.gray, style = 'italic' },
    Conceal = { fg = colors.foreground },
    Conditional = { link = 'Statement' },
    Constant = { fg = colors.orange },
    Cursor = { fg = fg, bg = bg },
    lCursor = { fg = fg, bg = bg },
    CursorIM = { fg = fg, bg = bg },
    CursorColumn = { bg = colors.lightgray },
    CursorLine = { bg = colors.lightgray },
    CursorLineNr = { fg = colors.lightgray },
    Debug = { link = 'Special' },
    Define = { link = 'Preproc' },
    Delimiter = { link = 'Special' },
    Error = { fg = colors.red, style = 'undercurl' },
    ErrorMsg = { fg = colors.red },
    Exception = { link = 'Statement' },
    Float = { link = 'Number' },
    FloatBorder = { fg = colors.lightgray },
    Function = { fg = colors.pink },
    HelpCommand = { link = 'Statement' },
    HelpExample = { link = 'Statement' },
    Identifier = { fg = colors.lightyellow },
    Include = { link = 'Preproc' },
    IncSearch = { bg = colors.orange, fg = colors.black },
    Italic = { style = 'italic' },
    Keyword = { link = 'Statement' },
    Label = { link = 'Statement' },
    LineNr = { fg = colors.gray },
    Macro = { link = 'Preproc' },
    MatchParen = { fg = colors.lightyellow, style = 'bold' },
    ModeMsg = { fg = colors.gray },
    MoreMsg = { fg = colors.gray },
    Normal = { fg = colors.foreground, bg = colors.background },
    NormalNC = { fg = colors.foreground, bg = colors.background },
    NormalSB = { fg = colors.foreground, bg = colors.background },
    NormalFloat = { fg = colors.foreground, bg = colors.darkgray },
    NonText = { fg = colors.background },
    Number = { link = 'Constant' },
    Operator = { link = 'Statement' },
    Pmenu = { bg = colors.black, fg = colors.foreground },
    PmenuSel = { bg = colors.gray },
    PmenuSbar = { bg = colors.lightgray },
    PmenuThumb = { bg = colors.lightgray },
    PreCondit = { link = 'Preproc' },
    PreProc = { fg = colors.lightblue },
    Question = { fg = colors.darkyellow },
    QuickFixLine = { bg = colors.gray, style = 'bold' },
    Repeat = { link = 'Statement' },
    Search = { bg = colors.gray, fg = colors.foreground },
    SignColumn = { bg = colors.background },
    Special = { fg = colors.bluegray },
    SpecialChar = { link = 'Special' },
    SpecialKey = { fg = colors.lightgray },
    SpecialComment = { fg = colors.bluegray },
    SpellBad = { sp = colors.red, style = 'undercurl' },
    SpellCap = { sp = colors.yellow, style = 'undercurl' },
    SpellLocal = { sp = colors.gray, style = 'undercurl' },
    SpellRare = { sp = colors.foreground, style = 'undercurl' },
    Statement = { fg = colors.lilac },
    StatusLine = { fg = colors.foreground, bg = colors.gray },
    StatusLineNC = { fg = colors.foreground, bg = colors.gray },
    StorageClass = { link = 'Type' },
    String = { fg = colors.lightgreen },
    Structure = { link = 'Type' },
    Tag = { link = 'Special' },
    Terminal = { link = 'Normal' },
    Title = { fg = colors.foreground },
    Todo = { bg = colors.background, fg = colors.bluegray },
    Type = { fg = colors.lightyellow },
    Typedef = { link = 'Type' },
    Underlined = { style = 'underline' },
    VertSplit = { bg = colors.background },
    VertSplit = { bg = colors.background },
    Visual = { bg = colors.gray },
    VisualNOS = { bg = colors.gray },
    WarningMsg = { fg = colors.bluegray },
    WildMenu = { bg = colors.background }
  }

  theme.plugins = {
    cmp = {}, -- TODO
    lsp = {
      DiagnosticError = { fg = colors.red },
      DiagnosticWarn = { fg = colors.yellow },
      DiagnosticInfo = { fg = colors.gray },
      DiagnosticHint = { fg = colors.foreground },
      DiagnosticUnderlineError = { style = 'undercurl', sp = colors.red }, 
      DiagnosticUnderlineWarn = { style = 'undercurl', sp = colors.yellow },
      DiagnosticUnderlineInfo = { style = 'undercurl', sp = colors.gray }, 
      DiagnosticUnderlineHint = { style = 'undercurl', sp = colors.foreground }, 
      DiagnosticVirtualTextError = { fg = colors.red }, 
      DiagnosticVirtualTextWarn = { fg = colors.yellow },
      DiagnosticVirtualTextInfo = { fg = colors.gray },
      DiagnosticVirtualTextHint = { fg = colors.foreground },
      LspActiveParameter = { fg = colors.orange },
      LspCodeLens = { link = 'Comment' },
      LspReferenceText = { bg = colors.gray },
      LspReferenceRead = { bg = colors.gray },
      LspReferenceWrite = { bg = colors.gray },
    },
    lualine = {}, -- TODO
    telescope = {}, -- TODO
    treesitter = {
      TSField = { fg = colors.foreground },
      TSInclude = { fg = colors.lilac },
      TSKeyword = { fg = colors.lilac },
      TSKeywordFunction = { fg = colors.lilac },
      TSLabel = { fg = colors.blue },
      TSOperator = { fg = colors.lilac },
      TSParameter = { fg = colors.foreground },
      TSProperty = { link = 'TSField' },
      TSPunctDelimiter = { fg = colors.blue },
      TSPunctBracket = { fg = colors.bluegray },
      TSPunctSpecial = { fg = colors.blue },
      TSStringRegex = { fg = colors.green },
      TSFuncMacro = { fg = colors.blue },
      TSNamespace = { fg = colors.lightblue }
    },
  }

  return theme
end

return M
